name: synthfaces
channels:
  - nvidia
dependencies:
  - python >= 3.8
  - pip
  - click>=8.0
  - pillow=8.4.0
  - scipy=1.7.1
  - cudatoolkit=11.1
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - matplotlib=3.4.2
  - imageio=2.9.0
  - pip:
    - torch==1.13.1
    - torchvision==0.14.1
    - numpy==1.22.4
    - imgui==1.3.0
    - glfw==2.2.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - opencv-python==4.7.0.72
    - scikit-image==0.19.3
    - scikit-learn==1.2.2
    - pyspng
    - psutil
    - tensorboardX
    - toml
    - easydict
    - timm
    - pymatting
    - gdown
    - onedrivedownloader
    - PySimpleGUI
